import Foundation
import Testing
@testable import Sotto

/// Pure logic for the separate clipboard-history store, the concealed-type skip
/// predicate, and the self-paste suppression guard.
@Suite struct ClipboardHistoryTests {
    private func entry(_ id: String = "x", _ text: String = "hello") -> ClipboardEntry {
        ClipboardEntry(id: id, date: Date(timeIntervalSince1970: 1000),
                       text: text, sourceApp: "Notes", bundleID: "com.apple.Notes")
    }

    // MARK: store

    @Test func encodeDecodeRoundTrip() {
        let line = ClipboardHistoryStore.encode(entry("a", "copied text"))!
        let decoded = ClipboardHistoryStore.decode(jsonl: line)
        #expect(decoded.count == 1)
        #expect(decoded[0].id == "a")
        #expect(decoded[0].text == "copied text")
        #expect(decoded[0].sourceApp == "Notes")
    }

    @Test func decodeSkipsMalformedLines() {
        let good = ClipboardHistoryStore.encode(entry())!
        #expect(ClipboardHistoryStore.decode(jsonl: good + "\nnot json\n{bad}\n").count == 1)
    }

    @Test func capKeepsNewestOnly() {
        let lines = (1...10).map { "\($0)" }
        #expect(ClipboardHistoryStore.capLines(lines, max: 3) == ["8", "9", "10"])
    }

    @Test func capNoOpUnderLimit() {
        let lines = ["1", "2"]
        #expect(ClipboardHistoryStore.capLines(lines, max: 50) == lines)
    }

    // MARK: concealed-type skip (password managers, transient)

    @Test func skipsConcealedAndTransient() {
        #expect(ClipboardHistoryMonitor.isSkippable(typeIdentifiers: ["org.nspasteboard.ConcealedType"]))
        #expect(ClipboardHistoryMonitor.isSkippable(typeIdentifiers: ["public.utf8-plain-text", "org.nspasteboard.TransientType"]))
        #expect(ClipboardHistoryMonitor.isSkippable(typeIdentifiers: ["org.nspasteboard.AutoGeneratedType"]))
    }

    @Test func capturesPlainText() {
        #expect(!ClipboardHistoryMonitor.isSkippable(typeIdentifiers: ["public.utf8-plain-text"]))
        #expect(!ClipboardHistoryMonitor.isSkippable(typeIdentifiers: []))
    }

    // MARK: self-paste suppression guard

    @Test func writeGuardIsOneShot() {
        let g = ClipboardWriteGuard()
        g.markOwnWrite(changeCount: 42)
        #expect(g.isOwnWrite(42))        // matched once
        #expect(!g.isOwnWrite(42))       // consumed — a later real copy at 42 is NOT suppressed
        #expect(!g.isOwnWrite(99))       // never stamped
    }

    @Test func writeGuardIsBounded() {
        let g = ClipboardWriteGuard()
        // Stamp far more than the cap (16); the oldest must be evicted, not leaked.
        for c in 1...100 { g.markOwnWrite(changeCount: c) }
        #expect(!g.isOwnWrite(1))        // long evicted
        #expect(g.isOwnWrite(100))       // newest retained
    }
}
