import AppKit
import Foundation

/// Continuously observes the general pasteboard and records user copies into the
/// (separate) clipboard history. Opt-in — AppDelegate only start()s it when the
/// setting is on. Polls `changeCount` (macOS has no pasteboard-change callback).
///
/// Deliberately NOT the `ClipboardMonitor` in ContextSnapshot.swift — that one is
/// scoped to a single dictation for the pre-record heuristic. This one runs for the
/// app's lifetime and serves a different feature.
@MainActor
final class ClipboardHistoryMonitor {
    private let pasteboard = NSPasteboard.general
    private let writeGuard: ClipboardWriteGuard
    private var timer: Timer?
    private var lastChangeCount: Int
    private var lastCapturedText: String?

    /// Pasteboard marker types that mean "do not store" — the community-standard
    /// conventions password managers (1Password/Bitwarden/KeePassXC) and secure
    /// fields set. Skipping these is the one non-negotiable secret guard.
    nonisolated private static let skipTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    init(writeGuard: ClipboardWriteGuard) {
        self.writeGuard = writeGuard
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    var isRunning: Bool { timer != nil }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount // ignore whatever's already on the clipboard
        lastCapturedText = nil
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        lastCapturedText = nil
    }

    private func poll() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        if writeGuard.isOwnWrite(current) { return }        // Sotto's own paste / restore / copy
        if shouldSkipCurrentItem() { return }               // password managers, transient
        guard let s = pasteboard.string(forType: .string) else { return }
        guard !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        guard s != lastCapturedText else { return }         // dedup consecutive identical copies
        lastCapturedText = s

        let capped = s.count > ClipboardHistoryStore.maxLength
            ? String(s.prefix(ClipboardHistoryStore.maxLength)) : s
        let front = NSWorkspace.shared.frontmostApplication
        ClipboardHistoryStore.append(ClipboardEntry(
            text: capped, sourceApp: front?.localizedName, bundleID: front?.bundleIdentifier))
    }

    /// A nil/empty item is treated as skippable (don't capture what we can't inspect).
    private func shouldSkipCurrentItem() -> Bool {
        guard let types = pasteboard.pasteboardItems?.first?.types else { return true }
        return Self.isSkippable(typeIdentifiers: types.map(\.rawValue))
    }

    /// Pure: does this set of pasteboard type identifiers mark a "do not store" item?
    nonisolated static func isSkippable(typeIdentifiers: [String]) -> Bool {
        typeIdentifiers.contains { skipTypes.contains($0) }
    }
}
